### ISSUE TITLE
能否支持自定义token自动刷新时间呢？

### ISSUE THREAD

**Issue by lexmin0412** [Elliott-Hu/JWTMiddleware#1]
## 问题描述

场景是如果secret设置了2h的过期时间，如果后续请求的时候token已经过期，middleware内部会判断是否在7天之内，如果是就会去自动刷新token，但我想把这个7天也作为自定义的配置传入，现在是没法做到的。

## 期望

能够提供自动刷新期限的配置参数。

**Comment by Elliott-Hu** [comment]
可以的，马上安排👍
